# -*- coding: utf-8 -*-
"""6_Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JTKCYwAAgfcy_oCjgLH9pGNGrAInT7Kk
"""

import heapq
inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 06/Input 3.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 06/Output 3.txt','w')
n,m=inp.readline().strip().split(' ')
G=[[] for i in range(int(n)+1)]

for a in range(int(m)):
    u,v,w=inp.readline().strip().split(' ')
    u,v,w=int(u),int(v),int(w)
    G[u].append((v, w))

col=['White']*(int(n)+1)
par=[-1]*(int(n)+1)
dis=[float('inf')]*(int(n)+1)

def DIJKSTRA(G,v):
    dis[v]=0
    priority_q=[]
    heapq.heappush(priority_q, (0, v))

    while priority_q:
        dist,cur_node = heapq.heappop(priority_q)
        for u,weight in G[cur_node]:
           if col[u]=='White':
                if max(dis[cur_node], weight) < dis[u]:
                    dis[u]=max(dis[cur_node], weight)
                    heapq.heappush(priority_q,(dis[u],u))
        col[cur_node]='Black'


DIJKSTRA(G,1)

if dis[int(n)] < float('inf'):
    print(dis[int(n)])
else:
    print("IMPOSSIBLE")

inp.close()
out.close()