# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kuNVJBpe0AnoBXTdI-8IiwZ6bVdNYRE_
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/input 3.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/output 3.txt','w')
t=inp.readline()
cur_arr=inp.readline().strip().split()
arr=[]
for x in cur_arr:
    arr.append(int(x))

def merge(a,b):
    i=0
    j=0
    k=0
    sorted_array=[0]*(len(a)+len(b))
    while i<len(a) and j <len(b):
        if a[i]<b[j]:
            sorted_array[k]=a[i]
            i+=1
            k+=1
        else:
            sorted_array[k]=b[j]
            j+=1
            k+=1

    while i<len(a):
        sorted_array[k]=a[i]
        i+=1
        k+=1
    while j<len(b):
        sorted_array[k]=b[j]
        j+=1
        k+=1
    return sorted_array

def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
       mid = len(arr)//2
       a1 = mergeSort(arr[:mid])
       a2 = mergeSort(arr[mid:])
       return merge(a1, a2)

out.write(f"{mergeSort(arr)}")
inp.close()
out.close()