# -*- coding: utf-8 -*-
"""TASK 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sV2PVF3VAs895l-EkmpA1dbElWZaANc
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 03/Input 4.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 03/Output 4.txt','w')


def Partition(arr,l,h):
    pivot=arr[l]
    i=l
    for j in range(i+1,h+1):
        if arr[j]<pivot:
            i+=1
            arr[i],arr[j]=arr[j],arr[i]
    arr[l], arr[i] = arr[i], arr[l]
    return i

def smallest(arr,l,h,k):
    if l==h:
        if l==k:
            return arr[l]
    else:
        p=Partition(arr,l,h)
        if p==k:
              return arr[p]
        elif p<k:
              return smallest(arr,p+1,h,k)
        else:
              return smallest(arr,l,p-1,k)
t1=inp.readline()
cur=inp.readline().strip().split(' ')
arr=[]
for x in cur:
    arr.append(int(x))
t2=inp.readline()
for a in range(int(t2)):
    x=inp.readline().strip()
    y=smallest(arr,0,int(t1)-1,int(x))
    out.write(f"{y-1}\n")

inp.close()
out.close()