# -*- coding: utf-8 -*-
"""8_task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pdHuC6K2ctLn9vKBU-OsGILdz5pPmcFW
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 08/input 2.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 08/output 2.txt','w')
n=int(inp.readline().strip())

f=[0]*(n+1)

def ways_no(n):
    if n==1:
        return 1
    else:
        f[0]=1
        f[1]=1

        for i in range(2,n+1):
            f[i]=f[i-1]+f[i-2]
        out.write(f'{f[n]}')
ways_no(n)
inp.close()
out.close()