# -*- coding: utf-8 -*-
"""7_task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fMooqdV4gH0uo4ovHmfwxeIE52HPQ_cn
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 07/input 1.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 07/output 1.txt','w')
n=int(inp.readline().strip())
G=[]

for a in range(n):
    s,e=inp.readline().strip().split(' ')
    s,e=int(s),int(e)
    G.append((s, e))

G.sort(key=lambda x:x[1])

task=[]
count=0
start=-1

for i in range(len(G)):
    if G[i][0]>=start:
        count+=1
        task.append(G[i])
        start=G[i][1]

out.write(f'{count}\n')
for x in range(len(task)):
    out.write(f'{task[x][0]} {task[x][1]} \n')

inp.close()
out.close()