# -*- coding: utf-8 -*-
"""TASK 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lj9RPVFT8-a7Jc0NrR4qQF10GXhmU4Pf
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 03/Input 3.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 03/Output 3.txt','w')
t=inp.readline()
cur_arr=inp.readline().strip().split(' ')
arr=[]
for x in cur_arr:
    arr.append(int(x))

def quickSort(arr,l,h):
    if l<h:
        p=partition(arr,l,h)
        quickSort(arr,l,p-1)
        quickSort(arr,p+1,h)
    return arr

def partition(arr,l,h):
    pivot=arr[l]
    i=l
    for j in range(i+1,h+1):
        if arr[j]<pivot:
            i+=1
            arr[i],arr[j]=arr[j],arr[i]
    arr[l], arr[i] = arr[i], arr[l]
    return i

out.write(f"{quickSort(arr,0,int(t)-1)}")
inp.close()
out.close()