# -*- coding: utf-8 -*-
"""04_Task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q1xzqReD6EmVbWSTBIyDkMeu0W3nPSfj
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/input 4.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/output 4.txt','w')
t=inp.readline().strip().split(' ')
G=[[] for i in range(int(t[0])+1)]

for a in range(int(t[1])):
    cur_line=inp.readline().strip().split(' ')
    u, v = int(cur_line[0]), int(cur_line[1])
    G[u].append(v)

red=[0]*(int(t[0])+1)
blue=[0]*(int(t[0])+1)

cycle=False

def DFS_Cycle(G,u):
    global cycle
    red[u]=1
    blue[u]=1
    for v in G[u]:
        if red[v]!=0:
            if blue[v]==1:
                cycle=True
        else:
            DFS_Cycle(G,v)
    blue[u]=0


DFS_Cycle(G, 1)
if cycle==True:
    out.write('yes')
else:
    out.write('No')
inp.close()
out.close()