# -*- coding: utf-8 -*-
"""04_Task 1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k280ofrRsQ_6lEWThKgKnXPsMw5_ayki
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/Input 1a.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/Output 1a.txt','w')
t=inp.readline().strip().split(' ')
arr=[[int(0) for i in range(int(t[0])+1)] for j in range(int(t[0])+1)]
for a in range(int(t[1])):
    cur_line=inp.readline().strip().split(' ')
    arr[int(cur_line[0])][int(cur_line[1])]=int(cur_line[2])
for k in arr:
    out.write(f'{k} \n')
inp.close()
out.close()