# -*- coding: utf-8 -*-
"""04_Task 1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13px2vvbQ9uCTRIJFxJusdfB-gWsV3k3s
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/input 1b.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/output 1b.txt','w')
t=inp.readline().strip().split(' ')
arr=[[int(0) for i in range(int(t[0])+1)] for j in range(int(t[0])+1)]

for a in range(int(t[1])):
    cur_line=inp.readline().strip().split(' ')

    x=int(cur_line[0])
    y=int(cur_line[1])
    z=int(cur_line[2])
    arr[x][y]=(y,z)

for b in range(int(t[0]) + 1):
    output = str(b) + " : "
    for c in arr[b]:
        if c!=0:

            output += f"({c[0]},{c[1]}) "
    output += '\n'
    out.write(output)
inp.close()
out.close()