# -*- coding: utf-8 -*-
"""TASK 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyq9Rlr2SAZe7WehFFVm1lv9MBcMqajn
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 03/Input 1.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 03/Output 1.txt','w')
t=inp.readline()
cur_arr=inp.readline().strip().split(' ')
arr=[]
for x in cur_arr:
    arr.append(int(x))
count=0
def merge(lArr, rArr):
    global count
    i= 0
    j=0
    k=0
    merged=[0]*(len(lArr)+len(rArr))
    while i<len(lArr) and j<len(rArr):
        if lArr[i]<=rArr[j]:
            merged[k]=lArr[i]
            i+=1
            k+=1
        else:
            merged[k]=rArr[j]
            j+=1
            k+=1
            count+=1
            count+=len(lArr[i+1:])

    while i < len(lArr):
        merged[k]=lArr[i]
        i+=1
        k+=1

    while j < len(rArr):
        merged[k]=rArr[j]
        j+=1
        k+=1

    return merged

def mergeSort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left = mergeSort(arr[:mid])
    right = mergeSort(arr[mid:])
    merged = merge(left, right)

    return merged


mergeSort(arr)
out.write(f"{count}")
inp.close()
out.close()