# -*- coding: utf-8 -*-
"""05_Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pG05DkBUM617_s2U1IKdBTQGiJtMM2dn
"""

from queue import PriorityQueue
q = PriorityQueue()

inp = open('/content/drive/MyDrive/CSE221 Lab/Lab 05/input_2.txt', 'r')
out = open('/content/drive/MyDrive/CSE221 Lab/Lab 05/output_2.txt', 'w')
n, m = inp.readline().strip().split(' ')

indegree = [0] * (int(n) + 1)
G = [[] for i in range(int(n) + 1)]

for a in range(int(m)):
    cur_line=inp.readline().strip().split(' ')
    u, v=int(cur_line[0]), int(cur_line[1])
    G[u].append(v)
    indegree[v]+=1

path = []
cycle = False
red = [0]*(int(n)+1)
blue = [0]*(int(n)+1)

def Cycle_Check(u):
    global cycle
    red[u]=1
    blue[u]=1
    for v in G[u]:
        if red[v]!=0:
            if blue[v]==1:
                cycle=True
        else:
            Cycle_Check(v)
    blue[u]=0

for i in range(1, int(n) + 1):
    if not cycle:
        Cycle_Check(i)

def BFS(G):
    for i in range(1, int(n) + 1):
        if indegree[i]==0:
            q.put(i)
    while not q.empty():
        u = q.get()
        path.append(u)
        for v in G[u]:
            indegree[v]-=1
            if indegree[v]==0:
                q.put(v)

if cycle:
    out.write('IMPOSSIBLE')
else:
    BFS(G)

for i in path:
    out.write(f'{i} ')

inp.close()
out.close()