# -*- coding: utf-8 -*-
"""TASK 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K_JpI6k6U6ZHXcp0F3Cke1Pd7Kfkf84c
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 03/Input 2.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 03/Output 2.txt','w')
t=inp.readline()
a=inp.readline().strip().split(' ')
arr=[]
for j in a:
    arr.append(int(j))

def get_max(arr):
    n=len(arr)
    mid=n//2
    if n==1:
        return  -999999
    if n==2:
        return arr[0]+((arr[1])**2)

    left_max=get_max(arr[:mid])
    right_max=get_max(arr[mid:])

    maxl=max(arr[:mid])

    right=arr[mid:]
    maxr=right[0]
    for i in range(len(right)):
        if abs(right[i])>maxr:
            maxr=abs(right[i])
    cross_max=maxl+(maxr**2)

    return max(left_max,right_max,cross_max)


out.write(f"{get_max(arr)}")
inp.close()
out.close()