# -*- coding: utf-8 -*-
"""8_task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OeC8ogtdOwfSJ7RTNowSIbLLEoF05e-H
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 08/input 3.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 08/output 3.txt','w')
n,x=inp.readline().strip().split(' ')
n,x=int(n),int(x)
c=inp.readline().strip().split(' ')
coins=[]
for i in c:
    coins.append(int(i))

dp = [[-1 for i in range(n)] for j in range(x + 1)]

def coin_count(amount,idx,coins):
    if amount==0:
        return 0
    if idx>=n:
        return float('inf')
    if dp[amount][idx] != -1:
        return dp[amount][idx]

    taken=float('inf')
    not_taken=float('inf')
    if coins[idx] <= amount:
        taken= 1 + coin_count(amount-coins[idx], idx, coins)
    not_taken= coin_count(amount, idx+1, coins)
    dp[amount][idx] = min(taken, not_taken)
    return dp[amount][idx]

res=coin_count(x, 0, coins)

if res==float('inf'):
    out.write(f'{-1}')
else:
    out.write(f'{res}')

inp.close()
out.close()