# -*- coding: utf-8 -*-
"""05_Task_1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fDvX-h4SAX6M9qHbhtZcrjZxisirGS1Y
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 05/input_1A.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 05/output_1A.txt','w')
n,m=inp.readline().strip().split(' ')
G=[[] for i in range(int(n)+1)]

for a in range(int(m)):
    cur_line=inp.readline().strip().split(' ')
    u, v = int(cur_line[0]), int(cur_line[1])
    G[v].append(u)


col=['White']*(int(n)+1)
start=[0]*(int(n)+1)
finish=[0]*(int(n)+1)

time=0
cycle=False
stack = []

def DFS(G,s):
    global time
    global cycle
    col[s]='Grey'
    time+=1
    start[s]=time
    for u in G[s]:
        if col[u]=='White':
            DFS(G,u)
        elif col[u]=='Grey':
            cycle=True

    col[s]='Black'
    time+=1
    finish[s]=time
    stack.append(s)

def DFS_visit(G):
 for v in range(1,int(n)+1):
        if col[v]=='White':
            DFS(G,v)
            if cycle==True:
                out.write('IMPOSSIBLE')
                break

 else:
    stack.reverse()
    while len(stack)!=0:
        cur=stack.pop()
        out.write(f'{cur} ')

DFS_visit(G)
inp.close()
out.close()