# -*- coding: utf-8 -*-
"""7_task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10ceNq9BfBK-EY3-atzfXq-zhOMt_mc5M
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 07/input 3.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 07/output 3.txt','w')
n,k=inp.readline().strip().split(' ')
n,k=int(n),int(k)
G=[[] for i in range(n+1)]


V=[0]*(n+1)

def DFS(G, u):
    V[u] = 1
    size = 1
    for v in G[u]:
        if not V[v]:
            size+=DFS(G,v)
    return size

for x in range(k):
    a,b=inp.readline().strip().split(' ')
    a,b=int(a),int(b)
    G[a].append(b)
    G[b].append(a)
    V=[0]*(n+1)
    size=DFS(G, a)
    out.write(f'{size}\n')

inp.close()
out.close()