# -*- coding: utf-8 -*-
"""Task 2(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BkyV8hxMLvBSWyYTDkZiED1l9Fx60XtU
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/input 2.1.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/output 2.1.txt','w')
t1=inp.readline().strip()
arr1=inp.readline().strip().split(' ')

t2=inp.readline().strip()
arr2=inp.readline().strip().split(' ')

new_arr=[]
arr=arr1+arr2

for x in arr:
   new_arr.append(int(x))
def Merge(arr1,arr2):
    i=0
    j=0
    k=0
    sorted_array=[0]*(len(arr1)+len(arr2))
    while i<len(arr1) and j <len(arr2):
        if arr1[i]<arr2[j]:
            sorted_array[k]=arr1[i]
            i+=1
            k+=1
        else:
            sorted_array[k]=arr2[j]
            j+=1
            k+=1

    while i<len(arr1):
        sorted_array[k]=arr1[i]
        i+=1
        k+=1
    while j<len(arr2):
        sorted_array[k]=arr2[j]
        j+=1
        k+=1
    return sorted_array

def MergeSort(new_arr):
    if len(new_arr) <= 1:
        return new_arr
    else:
       mid = len(new_arr)//2
       left = MergeSort(new_arr[:mid])
       right = MergeSort(new_arr[mid:])
    return Merge(left, right)

out.write(f"{MergeSort(new_arr)}")
inp.close()
out.close()