# -*- coding: utf-8 -*-
"""6_Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1My5SBLPOeNE95zALAgTGwKWhCTkzwlmm
"""

import heapq
inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 06/Input 2.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 06/Output 2.txt','w')
n,m=inp.readline().strip().split(' ')
G=[[] for i in range(int(n)+1)]

for a in range(int(m)):
    u,v,w=inp.readline().strip().split(' ')
    u,v,w=int(u),int(v),int(w)
    G[u].append((v, w))

s1,s2=inp.readline().strip().split(' ')
s1,s2=int(s1),int(s2)

col=['White']*(int(n)+1)
par=[-1]*(int(n)+1)
dis=[float('inf')]*(int(n)+1)
store=[0]*(int(n)+1)

def Dijkstra(G,v):
    dis[v]=0
    priority_q=[]
    heapq.heappush(priority_q, (0, v))

    while priority_q:
        dist,cur_node = heapq.heappop(priority_q)
        for u,weight in G[cur_node]:
           if col[u]=='White':
                if dis[cur_node] + weight < dis[u]:
                    dis[u]=dis[cur_node] + weight
                    par[u]=cur_node
                    heapq.heappush(priority_q,(dis[u],u))
        col[cur_node]='Black'
Dijkstra(G,s1)
dis_s1= dis
par_s1 = par


col=['White']*(int(n)+1)
par=[-1]*(int(n)+1)
dis=[float('inf')]*(int(n)+1)


Dijkstra(G,s2)
dis_s2= dis

i = 0
j = 0
k=0

while i<len(dis_s1):
    if dis_s1[i] != float('inf') and dis_s2[j] != float('inf'):
        m=max(dis_s1[i],dis_s2[j])
        store[k]=(m,i)
        k+=1
    i+=1
    j+=1
priorityQ=[]
for i in store:
    if i != 0:
        heapq.heappush(priorityQ,i)
if len(priorityQ)!=0:
    p = heapq.heappop(priorityQ)
    out.write(f'Time : {p[0]} \nNode : {p[1]}' )
else:
    out.write('IMPOSSIBLE')

inp.close()
out.close()