# -*- coding: utf-8 -*-
"""Task 1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CmtR6BP6PKjcuNR2xy6eEFEFdDrU_t1K
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/input 1.2.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/output 1.2.txt', 'w')
t=inp.readline().strip().split(' ')
sum=int(t[1])
cur_num=inp.readline().split(' ')

exist=False

for i in range(len(cur_num)):
    temp=sum-int(cur_num[i])
    b=sorted(cur_num[i+1:])

    l=0
    r=len(b)-1
    while l<=r:
        mid=(l+r)//2
        if temp==int(b[mid]):
          out.write(f'{i+1} {mid+1}')
          exist=True
          break
        elif temp>int(b[mid]):
          l=mid+1
        else:
          r=mid-1
    break


if not exist:
    out.write('IMPOSSIBLE')
inp.close()
out.close()