# -*- coding: utf-8 -*-
"""6_Task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rH2wNLGaZ_TMXWTfqwh1wfCBgashXwnF
"""

import heapq
inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 06/Input_1.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 06/Output_1.txt','w')
n,m=inp.readline().strip().split(' ')
G=[[] for i in range(int(n)+1)]

for a in range(int(m)):
    u,v,w=inp.readline().strip().split(' ')
    u,v,w=int(u),int(v),int(w)
    G[u].append((v, w))

s=int(inp.readline())

col=['White']*(int(n)+1)
par=[-1]*(int(n)+1)
dis=[float('inf')]*(int(n)+1)

def dijkstra(G,v):
    dis[v]=0
    priority_q=[]
    heapq.heappush(priority_q, (0, v))

    while priority_q:
        dist,cur_node = heapq.heappop(priority_q)
        for u,weight in G[cur_node]:
           if col[u]=='White':
                if dis[cur_node] + weight < dis[u]:
                    dis[u]=dis[cur_node] + weight
                    par[u]=cur_node
                    heapq.heappush(priority_q,(dis[u],u))
        col[cur_node]='Black'

dijkstra(G,s)

for i in range(1, int(n) + 1):
    if dis[i]==float('inf'):
        out.write(f'{-1} ')
    else:
        out.write(f'{dis[i]} ')
inp.close()
out.close()