# -*- coding: utf-8 -*-
"""04_Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jevrj5jkvdC_H5Vn3Mywjpf4bRgCv3JP
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/input 3.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/output 3.txt','w')
t=inp.readline().strip().split(' ')
G=[[] for i in range(int(t[0])+1)]

for a in range(int(t[1])):
    cur_line=inp.readline().strip().split(' ')
    u, v = int(cur_line[0]), int(cur_line[1])
    G[u].append(v)
    G[v].append(u)

V= [0]*(int(t[0])+1)

def DFS(G, u):
    V[u] = 1
    out.write(f'{u} ')
    for v in G[u]:
        if not V[v]:
            DFS(G,v)

DFS(G, 1)
inp.close()
out.close()