# -*- coding: utf-8 -*-
"""04_Task 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dn7O_fyCkcxwZxbUKFrh_uq7WaTHwf_0
"""

from queue import Queue
q = Queue()

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/input 5.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/output 5.txt','w')
t=inp.readline().strip().split(' ')
G=[[] for i in range(int(t[0])+1)]

for a in range(int(t[1])):
    cur_line=inp.readline().strip().split(' ')
    u, v = int(cur_line[0]), int(cur_line[1])
    G[u].append(v)
    G[v].append(u)
d=int(t[2])

col=['White']*(int(t[0])+1)
par=[0]*(int(t[0])+1)
dis=[0]*(int(t[0])+1)
path=[]
def shortest_path(G,s):
    col[s]='Grey'
    q.put(s)

    while not q.empty():
        u = q.get()
        for x in G[u]:
            if col[x]=='White' :
                col[x]='Grey'
                dis[x]=dis[u]+1
                par[x]=u
                q.put(x)
        col[u]='Black'
    path.append(d)
    cur=d
    while par[cur]!=0:
        path.append(par[cur])
        cur=par[cur]
    path.reverse()
    return path

shortest_path(G,1)
out.write(f'Time: {dis[d]} \n')
out.write(f'Shortest Path: ')
for k in path:
    out.write(f'{k} ')

inp.close()
out.close()