# -*- coding: utf-8 -*-
"""Task 1(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mcw-BxIwMPU_16aoM1jr1Nl5qu4pqoJD
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/input 1.1.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/output 1.1.txt','w')
t=inp.readline().strip().split(' ')
cur_num=inp.readline().split(' ')
check=int(t[1])
exist=False
for i in range(len(cur_num)):
    for j in range(1,len(cur_num)):
        sum=int(cur_num[i])+int(cur_num[j])
        if sum==check:
           out.write(f'{i+1} {j+1}')
           exist=True
        break
if not exist:
    out.write('IMPOSSIBLE')
inp.close()
out.close()