# -*- coding: utf-8 -*-
"""Task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-nvTQuRmm8G10rurprKG_6vUFf6YJ4eG
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/input 4.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 02/output 4.txt','w')
t=inp.readline()
cur_arr=inp.readline().strip().split()
arr=[]
for x in cur_arr:
    arr.append(int(x))

def findMAx(arr,l,h):
    if l==h:
        return arr[l]
    elif l==h-1:
        if arr[l]>arr[h]:
            return arr[l]
        else:
            return arr[h]
    else:
     mid = (l+h)//2
    left_max = findMAx(arr, l, mid)
    right_max = findMAx(arr, mid + 1, h)

    return max(left_max, right_max)


out.write(f"{findMAx(arr,0,int(t)-1)}")
inp.close()
out.close()