# -*- coding: utf-8 -*-
"""04_Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TYHvdKLaQ5itLBPg2s3TnHqRQlAonO2q
"""

from queue import Queue
q = Queue()

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/input 2.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/output 2.txt','w')
t=inp.readline().strip().split(' ')
N,M=int(t[0]),int(t[1])
G=[[] for i in range(N+1)]

for a in range(M):
    cur_line=inp.readline().strip().split(' ')
    u,v=int(cur_line[0]), int(cur_line[1])
    G[u].append(v)
    G[v].append(u)

colour=[0]*(N+1)
def BFS(G,s):
    colour[s]=1
    q.put(s)

    while not q.empty():
        u = q.get()
        out.write(f'{u} ')
        for x in G[u]:
            if colour[x]==0 :
                colour[x]=1
                q.put(x)

BFS(G,1)
inp.close()
out.close()