# -*- coding: utf-8 -*-
"""04_Task 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RmsbBHzlEWHFzHPDpsr51hsinby_LPpy
"""

inp=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/input 6.txt','r')
out=open('/content/drive/MyDrive/CSE221 Lab/Lab 04/output 6.txt','w')
r,c=inp.readline().strip().split(' ')
grid=[['#' for i in range(int(c) + 2)] for j in range(int(r) + 2)]

for i in range(1,int(r)+1):
    cur_line=inp.readline().strip()
    for j in range(1,int(c)+1):
        grid[i][j]=(cur_line[j-1])

visited=[[int(0) for i in range(int(c)+2)] for j in range(int(r)+2)]
for i in range(int(r)+2):
  for j in range(int(c)+2):
    if grid[i][j]=='#':
        visited[i][j]=-1
    else:
        visited[i][j]=0

def DFS(i, j):
    temp_count=0
    if grid[i][j]=='D':
           temp_count+=1
    visited[i][j]=1
    move=[[i - 1, j], [i + 1, j], [i, j + 1], [i, j - 1]]
    for k in move:
        if visited[k[0]][k[1]] == 0:
            temp_count+=DFS(k[0], k[1])
    return temp_count

count=0
for i in range(int(r)+2):
  for j in range(int(c)+2):
    if grid[i][j]=='.' and visited[i][j]==0:
      temp_count=DFS(i, j)
      count=max(count,temp_count)
out.write(f'{count}')
inp.close()
out.close()